let express=require("express")
const postReq = require("../CONTROLLERS/postReq")
const getReq =require("../CONTROLLERS/getReq")
const getReqById = require("../CONTROLLERS/getreqById")
const deletReq = require("../CONTROLLERS/deleteRq")
const putReq = require("../CONTROLLERS/putREq")
const patchReq = require("../CONTROLLERS/patchReq")
let rout=express.Router()
rout.post("/add",postReq)
rout.get("/getdata",getReq)
rout.get("/getbyid/:id",getReqById)
rout.delete("/delete/:id",deletReq)
rout.put("/update/:id",putReq)
rout.patch("/patch/:id",patchReq)
module.exports=rout